image: docker:latest
services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy

build:
    stage: build
    only:
      - master
      - dev
    script:
      - docker-compose build
      - docker-compose push

deploy:
    environment: front_production
    stage: deploy
    only:
      - master
    script:
      - docker-compose up -d
