image: docker:latest
services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy
  - cleanup

build:
    stage: build
    only:
      - master
      - dev
    script:
      - docker-compose build
      - docker-compose push

deploy:
    environment: front_production
    stage: deploy
    only:
      - master
    script:
      - docker-compose run web

cleanup:
  stage: cleanup
  script:
    - docker rm $(docker ps -aq -f status=exited) || echo "fail"
    - docker rmi $(docker images -f dangling=true -q) || echo "fail"